version: "3.8"
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    depends_on:
      - ollama
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  ollama_data:
