# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /backend

# Copy the requirements file into the container
COPY requirements.txt requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Copy the rest of the application code into the container
COPY . .

# Set the environment variable for Flask
ENV PORT=5000
ENV OLLAMA_API_URL=http://ollama:11434


EXPOSE 5000

# Run the application
CMD ["python", "-u", "app.py"]